### ISSUE TITLE
Dataset for CMU-MOSEI?

### ISSUE THREAD

**Issue by paraanggotaforum** [ongdisheng/Multimodal-Sentiment-Analysis#1]
Hi there, sorry for bothering you. Is it true that you got CMU-MOSEI data from here? https://drive.google.com/drive/folders/1A_hTmifi824gypelGobgl2M-5Rw9VWHv

Thank you!

**Comment by paraanggotaforum** [comment]
May I know where you got the raw text data too?

**Comment by ongdisheng** [comment]
Hi, 

All the datasets used are taken from THUIAR Lab [here](https://drive.google.com/drive/folders/1E5kojBirtd5VbfHsFp6FYWkQunk73Nsv). To retrieve raw text data, you can simply load the pickle file and access it using `["train"]["raw_text"]` since the features of dataset are organized as such:
```python
{
    "train": {
        "raw_text": [],
        "audio": [],
        "vision": [],
        "id": [],                     # [video_id$_$clip_id, ..., ...]
        "text": [],
        "text_bert": [],
        "audio_lengths": [],
        "vision_lengths": [],
        "annotations": [],
        "classification_labels": [], # Negative(< 0), Neutral(0), Positive(> 0)
        "regression_labels": []
    },
    "valid": {***}, # same as the "train" 
    "test": {***},  # same as the "train"
}
```

Hope this helps.
